image:
- Visual Studio 2019
- macOS
- Ubuntu

skip_branch_with_pr: true
stack: python 3.11

environment:
  GITHUB_TOKEN:
    secure: Ti46nPnZgFh0nRteU6ma0EhJnCTW7PaMn9hnnewZl4gBFPyRQnXNCwGog02+MRLX

install:
- pip install -r requirements.txt

build_script:
- flet pack main.py --name CFWKG --icon icon.png --product-name CFWKG --product-version "1.0.5" --copyright "Copyright (c) 2023 Pegioner Inc."

test: off

# Publish artifacts to GitHub Releases on "tag" builds
deploy:
  provider: GitHub
  auth_token: $(GITHUB_TOKEN)
  on:
    APPVEYOR_REPO_TAG: true

#
#   Windows package
# 
for:
-
  matrix:
    only:
    - image: Visual Studio 2019

  after_build:
  - 7z a CFWKG-windows.zip %CD%\dist\*.exe

  artifacts:
  - path: CFWKG-windows.zip

#
#   macOS package
# 
-
  matrix:
    only:
    - image: macOS

  after_build:
  - tar -czvf CFWKG-macos.tar.gz -C dist CFWKG.app

  artifacts:
  - path: CFWKG-macos.tar.gz

#
#   Linux package
# 
-
  matrix:
    only:
    - image: Ubuntu

  after_build:
  - tar -czvf CFWKG-linux.tar.gz -C dist counter

  artifacts:
  - path: CFWKG-linux.tar.gz

